In [19]:
import numpy as np

def GENP(A, b):
    '''
    Gaussian elimination with no pivoting.
    % input: A is an n x n nonsingular matrix
    %        b is an n x 1 vector
    % output: x is the solution of Ax=b.
    % post-condition: A and b have been modified. 
    '''
    n =  len(A)
    if b.size != n:
        raise ValueError("Invalid argument: incompatible sizes between A & b.", b.size, n)
    for pivot_row in  range(n-1):
        for row in  range(pivot_row+1, n):
            multiplier = A[row][pivot_row]/A[pivot_row][pivot_row]
            #the only one in this column since the rest are zero
            A[row][pivot_row] = multiplier
            for col in range(pivot_row + 1, n):
                A[row][col] = A[row][col] - multiplier*A[pivot_row][col]
            #Equation solution column
            b[row] = b[row] - multiplier*b[pivot_row]
    print(A)
    print(b)
    x = np.zeros(n)
    k = n-1
    x[k] = b[k]/A[k,k]
    while k >= 0:
        x[k] = (b[k] - np.dot(A[k,k+1:],x[k+1:]))/A[k,k]
        k = k-1
    return x

def GEPP(A, b):
    '''
    Gaussian elimination with partial pivoting.
    % input: A is an n x n nonsingular matrix
    %        b is an n x 1 vector
    % output: x is the solution of Ax=b.
    % post-condition: A and b have been modified. 
    '''
    n =  len(A)
    if b.size != n:
        raise ValueError("Invalid argument: incompatible sizes between A & b.", b.size, n)
    # k represents the current pivot row. Since GE traverses the matrix in the upper 
    # right triangle, we also use k for indicating the k-th diagonal column index.
    for k in range(n-1):
        #Choose largest pivot element below (and including) k
        maxindex = abs(A[k:,k]).argmax() + k
        if A[maxindex, k] == 0:
            raise ValueError("Matrix is singular.")
        #Swap rows
        if maxindex != k:
            A[[k,maxindex]] = A[[maxindex, k]]
            b[[k,maxindex]] = b[[maxindex, k]]
        for row in range(k+1, n):
            multiplier = A[row][k]/A[k][k]
            #the only one in this column since the rest are zero
            A[row][k] = multiplier
            for col in range(k + 1, n):
                A[row][col] = A[row][col] - multiplier*A[k][col]
            #Equation solution column
            b[row] = b[row] - multiplier*b[k]
    print(A)
    print(b)
    x = np.zeros(n)
    k = n-1
    x[k] = b[k]/A[k,k]
    while k >= 0:
        x[k] = (b[k] - np.dot(A[k,k+1:],x[k+1:]))/A[k,k]
        k = k-1
    return x

In [26]:
a = np.array([[1,2,3], [9,50,6], [7,8,9]], float)
b =  np.array([23, 2, 3], float)

In [27]:
a, b

(array([[ 1.,  2.,  3.],
        [ 9., 50.,  6.],
        [ 7.,  8.,  9.]]),
 array([23.,  2.,  3.]))

In [28]:
GEPP(a, b)

[[  9.          50.           6.        ]
 [  0.77777778 -30.88888889   4.33333333]
 [  0.11111111   0.11510791   1.83453237]]
[ 2.          1.44444444 22.61151079]


array([-17.34117647,   1.68235294,  12.3254902 ])

In [49]:
np.linalg.solve(a, b)

ValueError: solve: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m,n)->(m,n) (size 1 is different from 10)

In [34]:
np.set_printoptions(precision=6)
a = np.random.randn(10, 10)
a

array([[ 1.491881,  0.651457,  0.047414,  0.456795, -1.023129,  1.241224,
        -0.010898,  0.767149,  1.985981, -0.257956],
       [-0.17944 ,  0.724406,  0.840021,  0.266869,  0.684371, -0.044924,
        -0.304086, -0.76873 ,  0.790368,  0.447817],
       [-0.371179,  0.934583,  0.351688,  1.671083,  0.192702, -0.927701,
        -1.958715, -0.968374, -0.842763, -0.368496],
       [-0.86944 ,  0.333685,  0.62182 , -1.150721,  0.352142,  0.006428,
         1.400686, -2.475137, -0.672098, -1.496498],
       [-0.509198, -0.834308,  1.360829, -0.399319,  0.243808,  0.592308,
        -0.58286 , -0.250973,  0.146439, -1.098776],
       [-0.743924,  0.4363  ,  0.27362 ,  0.439097, -2.019041, -0.293689,
         0.181448, -1.157241,  0.816425, -0.286322],
       [ 0.809364, -0.616299, -0.37616 ,  0.513292,  0.99002 , -0.116785,
        -1.555809, -0.882188, -0.069017, -0.010629],
       [-0.809671,  0.105263,  0.325037,  0.083329, -1.723855, -2.04296 ,
        -0.199242, -0.003231,  0.7510

In [53]:
b = np.random.randn(10, 1)

In [55]:
c = np.concatenate((a, b), 1)

In [56]:
a.shape

(10, 10)

In [57]:
b.shape

(10, 1)

In [58]:
c.shape

(10, 11)

In [59]:
GEPP(a, b)

[[ 1.537242 -1.367169 -1.155901  0.328549 -1.036223 -0.901195  0.019408
   0.108507  1.164968 -0.969897]
 [ 0.970492  1.978283  1.169206  0.137941 -0.017483  2.115826 -0.029733
   0.661844  0.85539   0.683321]
 [-0.420439 -0.789006  1.743047 -1.007476 -0.131398  1.772516  0.330219
   0.530772  1.543864 -1.009488]
 [-0.241457  0.305553 -0.163316  1.543728 -0.073619 -1.502318 -1.891014
  -1.05772  -0.570702 -0.976341]
 [-0.483934 -0.113897 -0.087543  0.340479 -2.508933  0.177856  0.860212
  -0.622753  1.807085 -0.433811]
 [-0.526704 -0.310789  0.045665  0.223649  0.897834 -1.764681 -0.562744
   1.031064  0.065125 -0.54641 ]
 [ 0.526504  0.052329  0.098244  0.279887 -0.625774 -0.342622 -0.722153
  -0.766491  0.43406   0.37803 ]
 [-0.565584 -0.222195  0.130721 -0.519879  0.103196  0.603072 -0.871556
  -4.111558 -0.169109 -1.565079]
 [-0.116728  0.28551   0.213003  0.311216 -0.24684   0.351516 -0.879304
   0.466742  1.414664  1.806266]
 [-0.331242 -0.65065   0.997501  0.520959 -0.023362 -0.

array([-9.982855,  1.586776, -9.803658,  2.192694,  5.257419,  2.218635,
       -0.831253,  1.970867,  6.841414, -5.313627])

In [60]:
c

array([[ 1.537242, -1.367169, -1.155901,  0.328549, -1.036223, -0.901195,
         0.019408,  0.108507,  1.164968, -0.969897,  0.411147],
       [-0.17944 ,  0.724406,  0.840021,  0.266869,  0.684371, -0.044924,
        -0.304086, -0.76873 ,  0.790368,  0.447817,  0.554442],
       [-0.371179,  0.934583,  0.351688,  1.671083,  0.192702, -0.927701,
        -1.958715, -0.968374, -0.842763, -0.368496,  0.271639],
       [-0.86944 ,  0.333685,  0.62182 , -1.150721,  0.352142,  0.006428,
         1.400686, -2.475137, -0.672098, -1.496498, -0.233451],
       [-0.509198, -0.834308,  1.360829, -0.399319,  0.243808,  0.592308,
        -0.58286 , -0.250973,  0.146439, -1.098776, -1.031174],
       [-0.743924,  0.4363  ,  0.27362 ,  0.439097, -2.019041, -0.293689,
         0.181448, -1.157241,  0.816425, -0.286322, -0.192089],
       [ 0.809364, -0.616299, -0.37616 ,  0.513292,  0.99002 , -0.116785,
        -1.555809, -0.882188, -0.069017, -0.010629, -0.159698],
       [-0.809671,  0.105263,  0.3